apiVersion: v1
kind: Service
metadata:
  name: aimembqwen3vino
  namespace: {{ .Release.Namespace }}
  labels:
    app: aimembqwen3vino
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: aimembqwen3vino
