{{- if .Values.provider }}
{{- range .Values.provider }}
---
apiVersion: v1
kind: Service
metadata:
  name: embedding-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: embedding
    provider: {{ .name }}
spec:
  type: ClusterIP
  ports:
    {{- range .paths }}
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.containerPort }}
      protocol: TCP
      name: {{ . | replace "/" "" | replace "*" "" | lower }}
    {{- end }}
  selector:
    app: embedding
{{- end }}
{{- end }}
